-- Session 20: Verhaltensanalyse (Sascha 16.08., Punkt 15)
--
-- Zwei Quellen, bewusst getrennt:
--
--   1. Was die App ohnehin speichert — Tagebuch, Gewichte, Lektionen, Abos.
--      Daraus lassen sich Trichter, Bindung und Nutzung der Eingabewege
--      berechnen, ohne ein einziges zusaetzliches Datum zu erheben.
--   2. app_events fuer das, was nirgends landet: welcher Screen wird
--      geoeffnet, wo bricht das Onboarding ab, wird die Paywall gesehen aber
--      nicht gekauft, welche Suche findet nichts.
--
-- Datenschutz: In app_events stehen keine Inhalte. Keine Mahlzeiten, keine
-- Gewichte, keine Fotos, keine Freitexte der Nutzerin — die einzige Ausnahme
-- ist der Suchbegriff bei einer erfolglosen Lebensmittelsuche ("Skyr"), und
-- genau der ist der Zweck: er sagt uns, was in der Datenbank fehlt.
-- Loescht eine Nutzerin ihr Konto, wird user_id auf NULL gesetzt statt die
-- Zeile zu entfernen: die Statistik bleibt, die Person ist weg.
-- Die Nutzerin kann in Profil > Datenschutz widersprechen (analytics_opt_out).
--
-- Irina sieht ueber die stats_-Funktionen ausschliesslich Summen, nie eine
-- einzelne Zeile. Deshalb security definer mit Admin-Pruefung: sonst muesste
-- man ihr Leserechte auf food_logs geben, und damit auf jedes Fruehstueck.

-- ---------------------------------------------------------------------------
-- Widerspruch (Art. 21 DSGVO) — Schalter im Profil
-- ---------------------------------------------------------------------------

alter table public.profiles
  add column if not exists analytics_opt_out boolean not null default false;

-- ---------------------------------------------------------------------------
-- app_events
-- ---------------------------------------------------------------------------

create table public.app_events (
  id bigint generated by default as identity primary key,
  -- set null statt cascade: siehe Kopfkommentar (Statistik ueberlebt, Person nicht)
  user_id uuid references auth.users (id) on delete set null,
  -- Weissliste in der Datenbank, nicht nur im Client: ein Tippfehler im Namen
  -- wuerde die Auswertung still verfaelschen, und ein neues Ereignis soll
  -- bewusst per Migration dazukommen — so bleibt dokumentiert, was wir messen.
  -- Kein eigenes 'onboarding_step': Die Onboarding-Schritte sind eigene
  -- Screens, screen_view zaehlt sie bereits. stats_onboarding_steps() liest
  -- deshalb dort — ein zweites Ereignis waere dieselbe Zahl an zwei Orten.
  name text not null check (name in (
    'screen_view',
    'paywall_view',
    'paywall_plan_selected',
    'paywall_purchase_result',
    'paywall_voucher_result',
    'scan_started',
    'scan_result',
    'scan_saved',
    'search_no_hit',
    'recipe_open',
    'lesson_start',
    'training_start',
    'app_error'
  )),
  props jsonb not null default '{}',
  platform text check (platform in ('ios', 'android')),
  app_version text,
  created_at timestamptz not null default now()
);

create index app_events_name_time_idx on public.app_events (name, created_at desc);
create index app_events_user_time_idx on public.app_events (user_id, created_at desc);

alter table public.app_events enable row level security;

-- Schreiben darf jede angemeldete Nutzerin, aber nur auf den eigenen Namen.
-- Kein select, kein update, kein delete fuer Clients — auch nicht auf eigene
-- Zeilen: es gibt keinen Grund, warum die App ihr Protokoll zurueckliest.
create policy "app_events_insert_own" on public.app_events
  for insert with check (user_id = auth.uid());

-- ---------------------------------------------------------------------------
-- Aufbewahrung: 180 Tage. Fuer Trends reicht das, und was nicht da ist, kann
-- nicht abfliessen. Laeuft naechtlich per pg_cron (Extension aus der
-- Push-Migration vom 06.08.).
-- ---------------------------------------------------------------------------

create or replace function public.prune_app_events()
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  n integer;
begin
  delete from public.app_events where created_at < now() - interval '180 days';
  get diagnostics n = row_count;
  return n;
end;
$$;

revoke execute on function public.prune_app_events() from public, anon, authenticated;

select cron.schedule(
  'irifit-prune-app-events',
  '20 3 * * *',
  $$select public.prune_app_events()$$
);

-- ---------------------------------------------------------------------------
-- Auswertungen
--
-- Alle Funktionen: security definer, Admin-Pruefung als erste Anweisung,
-- Rueckgabe ausschliesslich Summen. plpgsql und nicht sql, damit die Pruefung
-- eine echte Anweisung ist — in einer sql-Funktion haenge sie im FROM und
-- koennte vom Planer wegoptimiert werden.
-- ---------------------------------------------------------------------------

create or replace function public.assert_admin()
returns void
language plpgsql
stable
as $$
begin
  if not public.is_admin() then
    raise exception 'nur fuer Admin';
  end if;
end;
$$;

/* Trichter von der Anmeldung bis zur regelmaessigen Nutzung.
   aktiv_7_tage = hat in den letzten 7 Tagen etwas ins Tagebuch geschrieben. */
create or replace function public.stats_funnel()
returns table (
  registriert int,
  onboarding_fertig int,
  erster_eintrag int,
  aktiv_7_tage int,
  mit_abo int
)
language plpgsql
security definer
set search_path = public
as $$
begin
  perform public.assert_admin();
  return query
    select
      (select count(*) from auth.users)::int,
      (select count(*) from public.profiles where onboarding_completed_at is not null)::int,
      (select count(distinct fl.user_id) from public.food_logs fl)::int,
      (select count(distinct fl.user_id) from public.food_logs fl
        where fl.logged_on >= current_date - 6)::int,
      (select count(*) from public.subscriptions s
        where s.status in ('trialing', 'active', 'in_grace'))::int;
end;
$$;

/* Bindung nach Anmeldewoche: Wie viele der in Woche X angemeldeten Frauen
   waren in Woche X+1, X+2 … noch im Tagebuch? Die wichtigste Zahl fuer ein
   Abo-Produkt — sie sagt, ob die App traegt, bevor die Kuendigungen kommen. */
create or replace function public.stats_retention(p_weeks int default 8)
returns table (
  kohorte date,
  angemeldet int,
  woche_0 int,
  woche_1 int,
  woche_2 int,
  woche_3 int,
  woche_4 int
)
language plpgsql
security definer
set search_path = public
as $$
begin
  perform public.assert_admin();
  return query
    with kohorte as (
      select u.id, date_trunc('week', u.created_at)::date as woche
      from auth.users u
      where u.created_at >= date_trunc('week', now()) - make_interval(weeks => p_weeks - 1)
    ),
    aktiv as (
      select distinct k.id, k.woche,
        ((date_trunc('week', fl.logged_on::timestamp)::date - k.woche) / 7) as versatz
      from kohorte k
      join public.food_logs fl on fl.user_id = k.id
    )
    select
      k.woche,
      count(distinct k.id)::int,
      count(distinct case when a.versatz = 0 then a.id end)::int,
      count(distinct case when a.versatz = 1 then a.id end)::int,
      count(distinct case when a.versatz = 2 then a.id end)::int,
      count(distinct case when a.versatz = 3 then a.id end)::int,
      count(distinct case when a.versatz = 4 then a.id end)::int
    from kohorte k
    left join aktiv a on a.id = k.id
    group by k.woche
    order by k.woche desc;
end;
$$;

/* Tagesaktivitaet: aktive Nutzerinnen und Eintraege pro Tag. */
create or replace function public.stats_activity(p_days int default 30)
returns table (tag date, aktive int, eintraege int)
language plpgsql
security definer
set search_path = public
as $$
begin
  perform public.assert_admin();
  return query
    select fl.logged_on, count(distinct fl.user_id)::int, count(*)::int
    from public.food_logs fl
    where fl.logged_on >= current_date - (p_days - 1)
    group by fl.logged_on
    order by fl.logged_on desc;
end;
$$;

/* Welcher Eingabeweg wird wirklich benutzt? Scan, Barcode, Suche, Rezept,
   Favorit, manuell. Entscheidet, wo Arbeit sich lohnt. */
create or replace function public.stats_log_sources(p_days int default 30)
returns table (quelle text, anzahl int, anteil int)
language plpgsql
security definer
set search_path = public
as $$
begin
  perform public.assert_admin();
  return query
    select fl.source::text, count(*)::int,
      round(100.0 * count(*) / nullif(sum(count(*)) over (), 0))::int
    from public.food_logs fl
    where fl.logged_on >= current_date - (p_days - 1)
    group by fl.source
    order by count(*) desc;
end;
$$;

/* Die Rezepte, die tatsaechlich gekocht und getrackt werden. */
create or replace function public.stats_top_recipes(p_limit int default 15, p_days int default 90)
returns table (recipe_id bigint, titel text, protokolliert int, nutzerinnen int)
language plpgsql
security definer
set search_path = public
as $$
begin
  perform public.assert_admin();
  return query
    select r.id, r.title, count(*)::int, count(distinct fl.user_id)::int
    from public.food_logs fl
    join public.recipes r on r.id = fl.recipe_id
    where fl.recipe_id is not null
      and fl.logged_on >= current_date - (p_days - 1)
    group by r.id, r.title
    order by count(*) desc
    limit p_limit;
end;
$$;

/* Wo steigen die Frauen aus Irinas Kursen aus? Lektion fuer Lektion. */
create or replace function public.stats_course_dropoff()
returns table (kurs text, lektion text, nummer int, abgeschlossen int)
language plpgsql
security definer
set search_path = public
as $$
begin
  perform public.assert_admin();
  return query
    select c.title, l.title, l.sort_order, count(lp.user_id)::int
    from public.lessons l
    join public.courses c on c.id = l.course_id
    left join public.lesson_progress lp on lp.lesson_id = l.id
    where l.status = 'published'
    group by c.title, c.sort_order, l.title, l.sort_order
    order by c.sort_order, l.sort_order;
end;
$$;

/* Screen-Aufrufe aus app_events. */
create or replace function public.stats_screens(p_days int default 30)
returns table (screen text, aufrufe int, nutzerinnen int)
language plpgsql
security definer
set search_path = public
as $$
begin
  perform public.assert_admin();
  return query
    select e.props ->> 'screen', count(*)::int, count(distinct e.user_id)::int
    from public.app_events e
    where e.name = 'screen_view'
      and e.created_at >= now() - make_interval(days => p_days)
      and e.props ? 'screen'
    group by e.props ->> 'screen'
    order by count(*) desc;
end;
$$;

/* Onboarding: bis zu welchem Schritt kommen sie? Der Abfall zwischen zwei
   Zeilen ist der Absprung. Sortiert nach Reihenfolge im Ablauf, nicht nach
   Groesse — sonst sieht man den Absprung nicht.
   Wichtig beim Lesen: Wer vor der Kontoanlage (/account) abbricht, taucht hier
   nie auf. Die Ereignisse warten auf dem Geraet auf eine Nutzer-ID, die dann
   nie kommt. Die Zahlen vor /account sind also die Wege derer, die es bis zum
   Konto geschafft haben — kein Gesamtbild aller Startversuche. */
create or replace function public.stats_onboarding_steps(p_days int default 30)
returns table (schritt text, nutzerinnen int)
language plpgsql
security definer
set search_path = public
as $$
declare
  ablauf text[] := array[
    '/welcome', '/goal', '/basics', '/activity',
    '/preferences', '/result', '/account', '/paywall'
  ];
begin
  perform public.assert_admin();
  return query
    select e.props ->> 'screen', count(distinct e.user_id)::int
    from public.app_events e
    where e.name = 'screen_view'
      and e.created_at >= now() - make_interval(days => p_days)
      and e.props ->> 'screen' = any (ablauf)
    group by e.props ->> 'screen'
    order by array_position(ablauf, e.props ->> 'screen');
end;
$$;

/* Paywall: gesehen, Kauf ausgeloest, gekauft, abgebrochen, Gutschein. */
create or replace function public.stats_paywall(p_days int default 30)
returns table (
  gesehen int,
  kauf_versucht int,
  gekauft int,
  abgebrochen int,
  fehlgeschlagen int,
  gutschein int
)
language plpgsql
security definer
set search_path = public
as $$
begin
  perform public.assert_admin();
  return query
    select
      count(distinct case when e.name = 'paywall_view' then e.user_id end)::int,
      count(case when e.name = 'paywall_purchase_result' then 1 end)::int,
      count(case when e.name = 'paywall_purchase_result' and e.props ->> 'outcome' = 'success' then 1 end)::int,
      count(case when e.name = 'paywall_purchase_result' and e.props ->> 'outcome' = 'cancelled' then 1 end)::int,
      count(case when e.name = 'paywall_purchase_result' and e.props ->> 'outcome' = 'failed' then 1 end)::int,
      count(case when e.name = 'paywall_voucher_result' and e.props ->> 'ok' = 'true' then 1 end)::int
    from public.app_events e
    where e.created_at >= now() - make_interval(days => p_days);
end;
$$;

/* Suchbegriffe ohne Treffer — die Einkaufsliste fuer die Lebensmitteldatenbank. */
create or replace function public.stats_search_gaps(p_limit int default 30, p_days int default 60)
returns table (begriff text, anzahl int)
language plpgsql
security definer
set search_path = public
as $$
begin
  perform public.assert_admin();
  return query
    select lower(e.props ->> 'term'), count(*)::int
    from public.app_events e
    where e.name = 'search_no_hit'
      and e.created_at >= now() - make_interval(days => p_days)
      and coalesce(e.props ->> 'term', '') <> ''
    group by lower(e.props ->> 'term')
    order by count(*) desc
    limit p_limit;
end;
$$;

/* Scan-Trichter: gestartet, Ergebnis bekommen, uebernommen. Der Verlust
   zwischen Ergebnis und Uebernahme sagt, ob die KI daneben liegt. */
create or replace function public.stats_scan(p_days int default 30)
returns table (gestartet int, mit_ergebnis int, uebernommen int)
language plpgsql
security definer
set search_path = public
as $$
begin
  perform public.assert_admin();
  return query
    select
      count(case when e.name = 'scan_started' then 1 end)::int,
      count(case when e.name = 'scan_result' then 1 end)::int,
      count(case when e.name = 'scan_saved' then 1 end)::int
    from public.app_events e
    where e.created_at >= now() - make_interval(days => p_days);
end;
$$;

/* Stille Fehler in der App — sonst erfahren wir davon nur, wenn jemand schreibt. */
create or replace function public.stats_errors(p_days int default 14)
returns table (ort text, code text, anzahl int, nutzerinnen int)
language plpgsql
security definer
set search_path = public
as $$
begin
  perform public.assert_admin();
  return query
    select e.props ->> 'where', e.props ->> 'code', count(*)::int, count(distinct e.user_id)::int
    from public.app_events e
    where e.name = 'app_error'
      and e.created_at >= now() - make_interval(days => p_days)
    group by e.props ->> 'where', e.props ->> 'code'
    order by count(*) desc;
end;
$$;

-- Aufrufbar nur fuer angemeldete Rollen; die Admin-Pruefung sitzt in der
-- Funktion selbst. anon bleibt draussen.
do $$
declare
  f text;
begin
  foreach f in array array[
    'stats_funnel()',
    'stats_retention(int)',
    'stats_activity(int)',
    'stats_log_sources(int)',
    'stats_top_recipes(int, int)',
    'stats_course_dropoff()',
    'stats_screens(int)',
    'stats_onboarding_steps(int)',
    'stats_paywall(int)',
    'stats_search_gaps(int, int)',
    'stats_scan(int)',
    'stats_errors(int)'
  ]
  loop
    execute format('revoke execute on function public.%s from public, anon', f);
    execute format('grant execute on function public.%s to authenticated', f);
  end loop;
end;
$$;
